const {
  withDangerousMod,
  withAppBuildGradle,
  withInfoPlist,
  createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const packageJson = require('../package.json');
const IOS_MARKER = '# @generated by react-native-readium';
const READIUM_PODSPEC_SOURCE = 'https://github.com/Nohles/podspecs';
const IOS_LEGACY_SETUP = `${IOS_MARKER}\nsource '${READIUM_PODSPEC_SOURCE}'\nrequire File.join(File.dirname(\`node --print "require.resolve('react-native-readium/package.json')"\`.strip), 'scripts/readium_pods')\nrequire File.join(File.dirname(\`node --print "require.resolve('react-native-readium/package.json')"\`.strip), 'scripts/readium_post_install')\n`;
const IOS_LEGACY_READIUM_SOURCE = `${IOS_MARKER}\nsource 'https://github.com/readium/podspecs'\nrequire File.join(File.dirname(\`node --print "require.resolve('react-native-readium/package.json')"\`.strip), 'scripts/readium_pods')\nrequire File.join(File.dirname(\`node --print "require.resolve('react-native-readium/package.json')"\`.strip), 'scripts/readium_post_install')\n`;
const ANDROID_DEP_MARKER =
  '// @generated by react-native-readium: desugaring dependency';
const ANDROID_OPTIONS_MARKER =
  '// @generated by react-native-readium: desugaring options';

function createIosSetup(iosProjectRoot) {
  const packageRoot = path.resolve(__dirname, '..');
  const relativePackageRoot = path
    .relative(iosProjectRoot, packageRoot)
    .replaceAll(path.sep, '/');
  return `${IOS_MARKER}\nsource '${READIUM_PODSPEC_SOURCE}'\nsource 'https://cdn.cocoapods.org/'\nreadium_package_path = File.expand_path('${relativePackageRoot}', __dir__)\nrequire File.join(readium_package_path, 'scripts/readium_pods')\nrequire File.join(readium_package_path, 'scripts/readium_post_install')\n`;
}

function withReadiumPods(config) {
  return withDangerousMod(config, [
    'ios',
    async (modConfig) => {
      const podfilePath = path.join(
        modConfig.modRequest.platformProjectRoot,
        'Podfile'
      );
      const setup = createIosSetup(modConfig.modRequest.platformProjectRoot);
      let contents = fs.readFileSync(podfilePath, 'utf8');
      if (contents.includes(IOS_MARKER)) {
        if (contents.includes(IOS_LEGACY_SETUP)) {
          contents = contents.replace(IOS_LEGACY_SETUP, setup);
        } else if (contents.includes(IOS_LEGACY_READIUM_SOURCE)) {
          contents = contents.replace(IOS_LEGACY_READIUM_SOURCE, setup);
        } else if (!contents.includes("source 'https://cdn.cocoapods.org/'")) {
          contents = contents.replace(
            /source 'https:\/\/github\.com\/(?:readium|Nohles)\/podspecs'\n/,
            `source '${READIUM_PODSPEC_SOURCE}'\nsource 'https://cdn.cocoapods.org/'\n`
          );
        } else {
          contents = contents.replace(
            /source 'https:\/\/github\.com\/readium\/podspecs'\n/,
            `source '${READIUM_PODSPEC_SOURCE}'\n`
          );
        }
        fs.writeFileSync(podfilePath, contents);
        return modConfig;
      }

      contents = `${setup}${contents}`;

      const postInstall = /(\n\s*post_install do \|installer\|\s*\n)/;
      if (!postInstall.test(contents)) {
        throw new Error(
          'react-native-readium could not locate the CocoaPods post_install block.'
        );
      }
      contents = contents.replace(
        postInstall,
        `$1    readium_post_install(installer)\n`
      );

      const target = /(\n\s*target\s+['"][^'"]+['"]\s+do\s*\n)/;
      if (!target.test(contents)) {
        throw new Error(
          'react-native-readium could not locate the CocoaPods app target.'
        );
      }
      contents = contents.replace(target, `$1  readium_pods\n`);
      fs.writeFileSync(podfilePath, contents);
      return modConfig;
    },
  ]);
}

function withReadiumAndroidDesugaring(config) {
  return withAppBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.language !== 'groovy') {
      throw new Error(
        'react-native-readium currently supports Groovy Android app Gradle files.'
      );
    }

    let contents = modConfig.modResults.contents;
    if (!contents.includes(ANDROID_OPTIONS_MARKER)) {
      contents = contents.replace(
        /android\s*\{\s*\n/,
        `android {\n    ${ANDROID_OPTIONS_MARKER}\n    compileOptions {\n        coreLibraryDesugaringEnabled true\n    }\n`
      );
    }
    if (!contents.includes(ANDROID_DEP_MARKER)) {
      contents = contents.replace(
        /dependencies\s*\{\s*\n/,
        `dependencies {\n    ${ANDROID_DEP_MARKER}\n    coreLibraryDesugaring \"com.android.tools:desugar_jdk_libs:2.1.2\"\n`
      );
    }

    modConfig.modResults.contents = contents;
    return modConfig;
  });
}

function withReadiumIosBackgroundAudio(config) {
  return withInfoPlist(config, (modConfig) => {
    const modes = modConfig.modResults.UIBackgroundModes || [];
    modConfig.modResults.UIBackgroundModes = Array.from(
      new Set([...modes, 'audio'])
    );
    return modConfig;
  });
}

const withReadium = (config) => {
  config = withReadiumIosBackgroundAudio(config);
  config = withReadiumPods(config);
  return withReadiumAndroidDesugaring(config);
};

module.exports = createRunOncePlugin(
  withReadium,
  packageJson.name,
  packageJson.version
);
